NS2/MAC/uwUFetch/Packer  set 	t_bck_max_probe_Bits				16
NS2/MAC/uwUFetch/Packer  set 	t_bck_min_probe_Bits				16
NS2/MAC/uwUFetch/Packer  set 	n_cbeacon_tx_Bits					8
NS2/MAC/uwUFetch/Packer  set 	t_bck_choice_sensor_Bits			16
NS2/MAC/uwUFetch/Packer  set 	n_pck_sensor_want_tx_Bits			8
NS2/MAC/uwUFetch/Packer  set 	mac_addr_sensor_polled_Bits			2
NS2/MAC/uwUFetch/Packer  set 	n_pck_hn_want_tx_Bits				8
NS2/MAC/uwUFetch/Packer  set 	max_cbeacon_tx_hn_Bits				8
NS2/MAC/uwUFetch/Packer  set 	t_bck_max_rts_Bits					16
NS2/MAC/uwUFetch/Packer  set 	t_bck_min_rts_Bits					16
NS2/MAC/uwUFetch/Packer  set 	max_pck_want_rx_Bits				16
NS2/MAC/uwUFetch/Packer  set 	num_DATA_pcks_Bits					16
NS2/MAC/uwUFetch/Packer  set 	backoff_time_RTS_Bits				16
NS2/MAC/uwUFetch/Packer  set 	num_DATA_pcks_MAX_rx_Bits			16
NS2/MAC/uwUFetch/Packer  set 	mac_addr_HN_ctsed_Bits				16
