NS2/MAC/Uwpolling/Packer set t_in_Bits          	16
NS2/MAC/Uwpolling/Packer set t_fin_Bits         	16
NS2/MAC/Uwpolling/Packer set uid_TRIGGER_Bits       16
NS2/MAC/Uwpolling/Packer set id_polled_Bits     	8
NS2/MAC/Uwpolling/Packer set backoff_time_Bits  	16
NS2/MAC/Uwpolling/Packer set ts_Bits            	16
NS2/MAC/Uwpolling/Packer set n_pkts_Bits        	16
NS2/MAC/Uwpolling/Packer set uid_PROBE_Bits       	16
NS2/MAC/Uwpolling/Packer set id_node_Bits       	8
NS2/MAC/Uwpolling/Packer set uid_POLL_Bits       	16