# syntax=docker/dockerfile:1
FROM debian:10.10

RUN echo "deb http://deb.debian.org/debian buster main" > /etc/apt/sources.list
RUN echo "deb http://deb.debian.org/debian buster-updates main" >> /etc/apt/sources.list
RUN echo "deb-src http://deb.debian.org/debian buster main" >> /etc/apt/sources.list
RUN echo "deb-src http://deb.debian.org/debian buster-updates main" >> /etc/apt/sources.list

RUN dpkg --add-architecture armhf
RUN apt update && \
    apt -y upgrade && \
    apt install -y \
        build-essential \
        gcc-arm-linux-gnueabihf \
        g++-arm-linux-gnueabihf \
        gfortran-arm-linux-gnueabihf \
        autoconf \
        automake \
        libtool \
        flex \
        bison \
        autoconf-archive \
        gettext
WORKDIR /work
