---
opt:
        nn: 2
        starttime: 1
        stoptime: 100000
        propagation_speed: 1500
        maxinterval_: 20
        freq: 25000.0
        bw: 5000.0
        rngstream: 1
        ack_mode: "setNoAckMode"
Module/UW/CBR:
        packetSize_: 125
        period_: 60
        PoissonTraffic_: 1
        debug_: 0
MPropagation/Underwater:
        practicalSpreading_: 2
        debug_: 0
        windspeed_: 5
        shipping_: 1
Module/UW/PHYSICAL:
        BitRate_: 4800.0
        AcquisitionThreshold_dB_: 15.0
        RxSnrPenalty_dB_: 0
        TxSPLMargin_dB_: 0
        MaxTxSPL_dB_: 135.0
        MinTxSPL_dB_: 10
        MaxTxRange_: 200
        PER_target_: 0
        CentralFreqOptimization_: 0
        BandwidthOptimization_: 0
        SPLOptimization_: 0
        debug_: 0
