#!/bin/sh -e

# Copyright (c) 2022 Regents of the SIGNET lab, University of Padova.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the University of Padova (SIGNET lab) nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# @name_file:   run-crosscompile-env
# @author:      Maksym Komar
# @last_update: 2022.11.15
# @version:     0.0.1
# @brief_description: install required packages for crosscompilation

DEBIAN_RELEASE=bullseye

die() {
    printf "%s\n" $*
    exit 1
}
if [ $(id -u) != 0 ]; then
	die "need root"
fi


cat > /etc/apt/sources.list << END
deb http://deb.debian.org/debian $DEBIAN_RELEASE main
deb http://deb.debian.org/debian $DEBIAN_RELEASE-updates main

deb-src http://deb.debian.org/debian $DEBIAN_RELEASE main
deb-src http://deb.debian.org/debian $DEBIAN_RELEASE-updates main
END

dpkg --add-architecture armhf

apt update && \
    apt -y upgrade && \
    apt install -y \
        build-essential \
        gcc-arm-linux-gnueabihf \
        g++-arm-linux-gnueabihf \
        gfortran-arm-linux-gnueabihf \
        autoconf \
        automake \
        libtool \
        flex \
        bison \
        autoconf-archive \
        gettext
