#!/bin/sh
# todo: add packet header and clmessages

remove_from_list() {
  local list="$1"
  local to_remove="$2"
  local new_list=""
  
  for item in $list; do
    if [ "$item" != "$to_remove" ]; then
      if [ -z "$new_list" ]; then
        new_list="$item"
      else
        new_list="$new_list $item"
      fi
    fi
  done
  
  echo "$new_list"
}

if [ $# -lt 2 ]; then
    echo "Usage: $0 <module_name> \"<author_name>\""
    exit 1
fi

module_name=$1
author_name=$2

if [ ! -d "../DESERT_Framework/DESERT/$module_name/" ]; then
    cd ../DESERT_Framework/DESERT/
    mkdir "$module_name" && cd "$module_name" || exit 1
else 
    # rm -rf ../DESERT_Framework/DESERT/$module_name; # TODO: remove, used for debug purposes
    echo "Error, another module with the same name already exists."; exit 1
fi

current_year=$(date +%Y)

#### ---------------------------- Text blocks ---------------------------- ####
copyright_header_sh=$(cat << EOF
#
# Copyright (c) ${current_year} Regents of the SIGNET lab, University of Padova.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the University of Padova (SIGNET lab) nor the 
#    names of its contributors may be used to endorse or promote products 
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED 
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
EOF
)

copyright_header_cpp=$(echo "$copyright_header_sh" | sed 's/^#/ \/\//g')

### Makefile.am ###
# Logic for Initlib name (First letter uppercase)
addon_fuc="$(echo "$addon_name" | sed 's/./\U&/')"

text_makefile_am=$(cat << EOF
${copyright_header_sh}

AM_CXXFLAGS = -Wall -ggdb3

lib_LTLIBRARIES = lib${addon_name}.la

lib${addon_name}_la_SOURCES = initlib.cpp ${addon_name}.cpp

lib${addon_name}_la_CPPFLAGS = @NS_CPPFLAGS@ @NSMIRACLE_CPPFLAGS@ @DESERT_CPPFLAGS@$( [ "$has_deps" = true ] && echo " @DESERT_ADDON_CPPFLAGS@" )$( [ "$has_woss" = true ] && echo " @WOSS_CPPFLAGS@" )
lib${addon_name}_la_LDFLAGS = @NS_LDFLAGS@ @NSMIRACLE_LDFLAGS@ @DESERT_LDFLAGS@ @DESERT_LDFLAGS_BUILD@$( [ "$has_deps" = true ] && echo " @DESERT_ADDON_LDFLAGS@ @DESERT_ADDON_LDFLAGS_BUILD@" )$( [ "$has_woss" = true ] && echo " @WOSS_LDFLAGS@" )
lib${addon_name}_la_LIBADD = @NS_LIBADD@ @NSMIRACLE_LIBADD@ @DESERT_LIBADD@$( [ "$has_deps" = true ] && echo " @DESERT_ADDON_LIBADD@" )$( [ "$has_woss" = true ] && echo " @WOSS_LIBADD@" )

nodist_lib${addon_name}_la_SOURCES = initTcl.cc

BUILT_SOURCES = initTcl.cc

CLEANFILES = initTcl.cc

TCL_FILES =  ${addon_name}-init.tcl

initTcl.cc: Makefile \$(TCL_FILES)
		cat \$(VPATH)/\$(TCL_FILES) | @TCL2CPP@ ${addon_fuc}TclCode > initTcl.cc 

EXTRA_DIST = \$(TCL_FILES)
EOF
)
### Makefile.am ###

#### ---------------------------- Write files ---------------------------- ####
touch "${addon_name}.cpp" "${addon_name}.h"

printf "%s" "$text_autogen_file" > "autogen.sh"
chmod +x autogen.sh

printf "%s" "$text_configure_file" > "configure.ac"

printf "%s" "$text_makefile_am" > "Makefile.am"

printf "%s\n%s\n%s\n%s" "${copyright_header_sh}" \
	"# @file ${addon_name}-init.tcl" \
	"# @author ${author_name}" \
	"# @version 1.0.0" \
	> "${addon_name}-init.tcl"

printf "%s" "$text_initlib_file" > "initlib.cpp"

#### ------------------------------- Summary ------------------------------- ####
echo "------------------------------------------------"
echo "Addon '$addon_name' generated by $author_name."
echo "Dependencies: Modules ($module_deps) Addons ($addon_deps) WOSS ($has_woss)"
echo "------------------------------------------------"
