---
Module/UW/CBR:
        PER: 1
        throughput: 0
        sent_packets: 1
        received_packets: 1
Module/UW/TDMA:
        sent_packets: 1
        pippo: 1
        received_packets: 1
Module/UW/PHYSICAL:
        getTotPktsLost: 0
